development:
  adapter: mysql2
  database: my_database_development
  pool: 5
  timeout: 5000
test:
  adapter: mysql2
  database: my_database_test
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: heroku_708dd48ee268902
  host: us-cdbr-iron-east-05.cleardb.net
  username: b1ef00d6d37506
  password: 808e33a2
  pool: 5
  timeout: 5000